apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080        # Port to listen on for external traffic
      targetPort: 8080  # Port on the pods to forward traffic to
  type: NodePort
